- luna/gateware/interface/spi.py
Fix for https://github.com/greatscottgadgets/luna/issues/4
SPI state machine now moves back to IDLE when CS is released during a transaction.
> luna.gateware.inteface.spi: FSM move to IDLE when cs released

- docs/hardware/bringup_guide.rst
I think this is required - without it I was missing the sam headers that were in a submodule of tinyusb.
> docs: add --recursive to submodule init command

- luna/gateware/usb/usb2/transfer.py
This fixes an issue where the IN transfer manager could get stuck in
state WAIT_FOR_DATA if it entered that state just as a packet was
completing.
> gateware.usb2: also enter WAIT_TO_SEND if a packet is about to complete

- luna/gateware/platform/fomu.py
The production version (PVT) of Fomu has different pin definitions from both the Hacker and EVT versions. I copied the hacker platform class and changed the names and pin numbers to make it work.
> Added the Fomu PVT variant to the Fomu platform

- luna/gateware/interface/gateware_phy/phy.py
- luna/gateware/interface/gateware_phy/receiver.py
- luna/gateware/interface/spi.py
- luna/gateware/usb/usb2/endpoint.py
should be used for the history of samples. This avoid a problem where
the main "sync" domain gets used despite a DomainRenamer being used to
move LUNA to a different clock domain.
> Changed all uses of Rose, Fell, and Past to include which clock domain

- examples/phy/pipe_phy.py
- examples/phy/serdes_phy.py
- examples/usb/superspeed/simple_device.py
- luna/gateware/usb/devices/ila.py
It's the same typo that was fixed in: d67f1ab9e42d5a2034f199fe66fbdc4c47413c7c
then partially reintroduced in: cd40642c74c0a06c20d05474f3698708e3961802 and later.
> fix typo in USB ILA name

- luna/gateware/platform/de0_nano.py
Hi,
I just got the USB2 core working on the de0_nano.
I think this might be helpful to others with intel/altera boards.
Best regards,
Hans
> add board support for de0_nano (with USB3300 PHY)

- luna/gateware/stream/generator.py
The removed line made StreamSerializer pick the wrong byte for every transfer except the last, effectively breaking multi-byte transfers. Removing this line solves the problem.
Test case:
```python
m.d.comb += [
self.transmitter.stream.attach(self.interface.tx),
self.transmitter.data[0].eq(0x12),
self.transmitter.data[1].eq(0x34),
self.transmitter.data[2].eq(0x56),
self.transmitter.data[3].eq(0x78),
]
```
Before and after:
> gateware.stream: Fix multi-byte transfers with StreamSerializer

- luna/gateware/usb/usb2/transfer.py
A packet is complete either when it has reached the max packet size or the last flag is set.
We need to check both.
Fixes #105
> gateware.transfer: Fix corner case causing a potential lockup for short packets.

- luna/gateware/usb/usb2/control.py
The `endpoint_targeted` check seems to have been forgotten from the `DATA_OUT` state, but is required just like for the `DATA_IN` state.
Without this fix, the data stage handling will be skipped if another IN endpoint is polled between the setup and data stages:
With this patch, this situation is handled correctly:
> gateware.usb2.control: Ignore IN tokens destined for other endpoints.

- luna/gateware/usb/usb2/descriptor.py
> Only use .name property if type is of StandardDescriptorNumbers

- examples/usb/eptri/Makefile
- luna/gateware/stream/generator.py
- luna/gateware/usb/request/standard.py
- luna/gateware/usb/usb2/control.py
- luna/gateware/usb/usb2/device.py
- luna/gateware/usb/usb2/interfaces/eptri.py
Add possibility to pass a blacklist to StandardRequestHandler for packets to ignore, to be able to handle them in a different request handler.
> Add blacklist to StandardRequestHandler

- docs/custom_hardware.rst
Fixed the naming of the USB D- signal in the resource requirements table as it said 'd_m' when everything else says 'd_n'
> docs/customer_hardware.rst: USB D- signal naming

- luna/gateware/usb/request/standard.py
Bug found when implementing GET_STATUS, which returns two bytes.
> Data returned by handle_simple_data_request() is zero for all bytes beyond the first

- luna/gateware/usb/usb2/packet.py
This patch fixes #135 by resetting the `pid` field in USBTokenDetector and thereby the derived `is_out` field when tokens destined for other devices are detected. This makes `USBStreamOutEndpoint` correctly ignore following packet.
> gateware.usb2: Fix filtering in USBTokenDetector.

- luna/gateware/platform/__init__.py
- pyproject.toml
This calls the new close() method on ApolloDebugger to release the USB device after querying the device type. Without explicitly closing the USB device, Windows will not let another instance of ApolloDebugger claim the USB device and actually program the device. This requires merging https://github.com/greatscottgadgets/apollo/pull/6 and publishing version 0.0.5 of apollo-fpga first.
> Close ApolloDebugger USB connection after querying device version

- luna/gateware/usb/usb2/device.py
> gateware.usb2: USBDevice should have only one 'speed' signal

- luna/__init__.py
This avoids a dependency to amaranth_boards if not using any
pre-defined boards.
> Only load get_appropriate_platform when required

- luna/gateware/applets/analyzer.py
f4da0ed caused luna top module not import get_appropriate_platform by default, which broke the analyzer.
> gateware.applets.analyzer: fix import get_appropriate_platform

- luna/gateware/usb/request/standard.py
When a non-existent descriptor is requested, the descriptor handler is correctly STALLing the request, but the standard request handler remains stuck in the `GET_DESCRIPTOR` state, with the `expecting_ack` flag set. If an unrelated ACK then arrives before the next descriptor request, it's causing the descriptor handler to skip ahead into an invalid state, producing similar symptoms to #139.
Run e.g. `lsusb -v` while there's other IN activity ongoing. `lsusb` will attempt to request a debug descriptor, which will trigger this issue when it doesn't exist.
With an Orbtrace, the issue can be reproduced by starting a trace session with `orbuculum --orbtrace "-T4 -v3"` and then running `lsusb -vd 1209:3443 | grep iInterface` in another shell. Symptoms of this issue then looks like this: …
> gateware.request.standard: Correctly handle requests for non-existent descriptors.

- luna/gateware/applets/analyzer.py
- luna/gateware/usb/analyzer.py
- luna/gateware/usb/request/control.py
- luna/gateware/usb/request/standard.py
- luna/gateware/usb/usb2/endpoints/stream.py
- luna/gateware/usb/usb2/transfer.py
This PR adds an initial mechanism for the host to control LUNA's USB analyzer gateware, allowing capture to be started and stopped by software.
This is not intended to reflect any final design for the analyzer's USB control interface. It is just intended to be sufficient to close #149 and start making the analyzer more usable.
The changes are as follows:
1. Take some generic parts of `StandardRequestHandler`, and move them into a new `ControlRequestHandler` base class, which can also be used for vendor & class requests.
2. Add a vendor request handler to `USBAnalyzerApplet`, with requests allowing the host to read and write a register.
3. Add an enable signal to `USBAnalyzer`, and connect it to one bit of the host-controlled register.
These first changes are sufficient for the host to …
> Host controlled start/stop of USB analyzer capture

- luna/__init__.py
- luna/gateware/soc/memory.py
- luna/gateware/soc/simplesoc.py
The main upstream changes affecting SimpleSoC were:
1. Assigning a memory map to a bus freezes the memory 
2. The names of several mandatory SoC members have changed: `rom` -> `bootrom`, `ram` -> `scratchpad`
3. The addition of new, mandatory SoC properties: `mainram`, `sram`
4. `AsyncSerialPeripheral` construction has changed.
5. The bus `memory_map.windows()` method now returns an iterator over amaranth_soc.memory.MemoryMap rather than a tuple.
6. The memory map `all_resources()` method now returns an iterator over amaranth_soc.memory.ResourceInfo rather than a tuple.
Closes https://github.com/greatscottgadgets/luna/issues/167
Closes https://github.com/greatscottgadgets/luna/issues/187
> gateware.soc: bring SimpleSoC up to date with upstream changes to amaranth-soc and lambdasoc

- luna/gateware/applets/analyzer.py
Rather than the capture speed being a build-time setting, connect it to two bits of the control register we added in #164.
Bump the device descriptor version from 0.00 to 0.01 so that clients can detect that the additional bits are available.
> Analyzer: support capture speed selection by host

- luna/gateware/test/usb2.py
- luna/gateware/usb/usb2/__init__.py
This fixes a bug that was revealed recently due to Amaranth HDL changing how enumerations are converted to a `Value`, as their shape is now defined by the maximum value.
In particular, the `USBPacketID.byte()` method was returning a mangled `USBPacketID` instead of an `int`, and when assigned to an Amaranth HDL `Value` the upper bits were lost.
Fixes #198
> gateware.usb.usb2.USBPacketID: fix .byte() type

- luna/gateware/applets/analyzer.py
- luna/gateware/usb/analyzer.py
- luna/gateware/usb/usb2/endpoints/stream.py
- luna/gateware/usb/usb2/transfer.py
This PR fixes problems with stale data being read from the analyzer after capture is stopped and restarted.
Thanks to @miek for fixes!
> Discard data in FIFO and endpoint buffer when restarting analyzer

- applets/bulk_in_speed_test.py
- luna/gateware/applets/speed_test.py
This PR moves the gateware implementing the bulk IN speed test into the library, so that it can be reused in other ways.
Instead of having two versions of `USBInSpeedTestDevice` which are switched between based on the `LUNA_SUPERSPEED` environment variable, these are now separate `USBInSpeedTestDevice` and `USBInSuperSpeedTestDevice` implementations.
There should be no change to the behaviour of `bulk_in_speed_test.py`.
> Move speed test gateware into library

- luna/gateware/usb/usb2/descriptor.py
This PR fixes #217 by making sure an unsigned offset is passed to the `.word_select()` method.
Recent Amaranth HDL versions cast the subtraction to a `signed(3)` value, which is later rejected by `word_select()`. The `.as_unsigned()` method could also be used as a fix here, but inverting the value of `byte_in_stream` results in the same operation without a width extension.
> gateware.usb.usb2.descriptor: provide unsigned offset to .word_select()

- applets/interactive-test.py
- applets/ulpi-test.py
- examples/debugging/basic_ila.py
- examples/debugging/basic_ila_fast_domain.py
- examples/debugging/ila_shared_bus.py
- examples/hw_features/debug_spi.py
- examples/hw_features/uart_bridge.py
- examples/usb/stream_out_device.py
- luna/gateware/applets/dc_flash.py
- luna/gateware/architecture/car.py
The recent implementation of RFC-2 in Amaranth HDL caused some problems within LUNA: the code contains many instances of `Pin` used as a value.
This PR tries to fix all of them by referencing the internal signals instead (`.o`, `.i`, etc.).
> gateware: do not use Pin as a value

- applets/bulk_speed_test.py
- luna/gateware/applets/speed_test.py
This PR adds a new applet that is able to form a bi-directional bulk speed test.
I don't have access to SuperSpeed hardware so I thought it best to implement this separately to the `bulk_in_speed_test.py` applet for now.
New features added:
* Addition of a new OUT endpoint. (Added bonus: the speed test device will now enumerate under macOS)
* Vendor request handler to manage the switch between IN/OUT test.
* Data sent by the IN test is now an 8-bit counter rather than zeros.
* OUT test mirrors received data on device LED's and PMOD A.
There is one area where I am not 100% sure I'm doing the right thing in the gateware implementation and that is the logic for when a given IN or OUT test is inactive:
**IN test:**
https://github.com/antoinevg/luna/blob/791498f1eabb3632453770a5a3c5f7d3876e3c2a …
> applets: add a bi-directional bulk_speed_test applet

- luna/gateware/interface/flash.py
Allow instancing `ECP5ConfigurationFlashInterface` with a SPI bus that has an output-only chip select line.
This is in preparation for the refactor of https://github.com/greatscottgadgets/luna/pull/220: gateware will be moved to Apollo.
> interface.flash: allow SPI buses without bidirectional chip select line

- luna/gateware/interface/uart.py
- pyproject.toml
- requirements_test.txt
This updates the dependency on Amaranth to pin the newly-released version 0.4 instead of depending on the git version (which is currently broken as we rely on some components that have been removed).
I also removed the `amaranth-soc` dependency as that conflicts with the `amaranth` dependency. We could wait for them to update, but I don't think the dependency makes sense now that all the soc components have moved to [luna-soc](https://github.com/greatscottgadgets/luna-soc). The dependency was only kept at that time because the (unused) `UARTTransmitterPeripheral` class depends on it.
I also removed a few dependencies that were just completely unused, including `amaranth-stdio` that also conflicted.
> Pin Amaranth version 0.4 & clean-up dependencies

- luna/gateware/platform/__init__.py
We've recently settled on Python 3.8 as our minimum supported Python version for releases.
Python 3.8 does not however support `str | None` syntax as it was only introduced in 3.10.
This PR uses `typing.Optional` instead.
> Use Python 3.8 compatible type annotation for 'str | None'

- applets/hyperram_diagnostic.py
- applets/interactive-test.py
- luna/gateware/interface/psram.py
The new interface uses ECP5 DDR primitives instead of relying on a logic-generated clock signal.
Updates `interactive_test` and `hyperram_diagnostic` applets as well.
> gateware.interface.psram: update HyperRAM interface

- luna/gateware/applets/speed_test.py
This PR adds some optional constructor arguments to `USBSpeedTestDevice` that allow overriding the VID/PID, and disabling clock generation so that the code can be used as part of a larger design with its own clock arrangements.
Required by [cynthion-test](https://github.com/greatscottgadgets/cynthion-test), which builds a bitstream with the speed test gateware running on all three ports simultaneously.
> Additional constructor arguments for `USBSpeedTestDevice`

- luna/gateware/usb/usb2/device.py
Fixes name retrieval in new amaranth versions and fails silently when the bus name is not available.
> gateware.usb2: improve/fix retrieval of bus name for USB device hooks

- luna/gateware/platform/__init__.py
This ability was lost after 88ccb0983321bd0c694e0a10646191ad926ec913.
> platform: recover dynamic detection of the FPGA type, when possible

- luna/gateware/architecture/flash_sn.py
- luna/gateware/interface/flash.py
- luna/gateware/stream/generator.py
- luna/gateware/usb/request/standard.py
- luna/gateware/usb/usb2/descriptor.py
This PR adds the ability to use runtime / dynamic string descriptors that adhere to the `StreamSerializer` interface. 
The `ECP5FlashUIDStringDescriptor` module can be used to use the SPI Flash unique ID as a serial number for the device (hex-string): 
```python
d.iSerialNumber = ECP5FlashUIDStringDescriptor
```
This needs https://github.com/greatscottgadgets/python-usb-protocol/pull/31.
> gateware: add string descriptor for retrieving Flash UID at runtime

- luna/gateware/platform/core.py
Adds a `port_sharing` method to `LUNAApolloPlatform` which checks the port sharing method for a given PHY name.
> Add method to get Apollo port sharing method

- ci-scripts/build.sh
- pyproject.toml
This PR:
* Renames the `luna` pypi package name to `luna-usb`
* Adds missing package metadata
* Configures package for `setuptools-git-versioning`
* Removes unused dependency: `amaranth-boards`
* Removes unused dependency: `tox`
* Update CI build script to get `amaranth-boards` and `amaranth-stdio` via `cynthion[gateware]` instead.
> repo: update pyproject for initial pypi release

- pyproject.toml
This avoids including tests/examples and also any other build files that might be in the directory.
> Limit pyproject include mask to just the main package

- luna/gateware/usb/request/windows/__init__.py
- luna/gateware/usb/request/windows/ms_descriptor.py
This PR adds a request handler for Microsoft OS 1.0 descriptors.
https://github.com/greatscottgadgets/python-usb-protocol/pull/41
Add OS string descriptor to the `DeviceDescriptorCollection`. The byte after `MSFT100` defines the request value (`bMS_VendorCode`) for retrieving the OS descriptors:
```python
descriptors.add_descriptor(get_string_descriptor("MSFT100\xee"), index=0xee)
```
Then add the request handler to the control endpoint:
```python
msft_descriptors = MicrosoftOS10DescriptorCollection()
with msft_descriptors.ExtendedCompatIDDescriptor() as c:
with c.Function() as f:
f.bFirstInterfaceNumber = 0
f.compatibleID          = 'WINUSB'
control_ep.add_request_handler(MicrosoftOS10RequestHandler(msft_descriptors, request_code=0xee))
```
**NOTE:** If LUNA complains about …
> gateware.usb.request.windows: add MicrosoftOS10RequestHandler

- luna/gateware/usb/request/windows/__init__.py
Fixes the following issues:
- Handler must only claim requests with its specified request code.
- Recipient must be device for index 4, and interface for index 5.
- Don't generate stalls - that's handled by not claiming requests.
Tested with https://github.com/greatscottgadgets/cynthion/pull/94 on Windows 10.
> Fixes for Microsoft OS 1.0 descriptor request handler

- luna/gateware/usb/usb2/device.py
- luna/gateware/usb/usb2/reset.py
This draft PR adds a `disconnect` signal that, when pulled high by `USBDevice`, causes the UTMI interface's operating mode to be set to `NON_DRIVING` in order to trigger a host disconnect.
Open questions:
* Is this the best place to put the logic? e.g. Would it be better to tie it to the `USBResetSequencer` state machine and only operate if we're in state `LS_FS_NON_RESET` or `HS_NON_RESET`?
* ~~I've run into some weirdness where, after data has been transferred on any of the non control endpoints, I can no longer enumerate the device after disconnect/connect. This may however be due to a bug in my code. Currently investigating.~~  It was indeed a software bug.
> gateware.usb2: add disconnect signal to USBResetSequencer

- luna/gateware/usb/request/standard.py
Previously, enumeration would fail on a low-speed device:
```
[77942.213251] usb 2-2: new low-speed USB device number 106 using xhci_hcd
[77942.341327] usb 2-2: device descriptor read/64, error -75
[77942.577321] usb 2-2: device descriptor read/64, error -75
```
which translates to `EOVERFLOW 75 Value too large for defined data type.`
Looking on the scope, we found that the device was trying to return a longer packet than allowed for GetDescriptor requests:
This change makes sure to pass the max packet size through to the handler to set the limit correctly.
> gateware.usb.request.standard: pass max packet size to GetDescriptor handler

- luna/gateware/utils/cdc.py
- tests/test_cdc.py
In https://github.com/greatscottgadgets/luna/commit/db754379448e606c4e80bb499ef052abcaec4183 a subtle bug was introduced into cdc.synchronize where nested elements of type `Pin` with directionality `output` would be recursed into and end up being driven by `FFSynchronizer` rather than being skipped.
This would result in the signal being driven from multiple fragments: once from the top-level design and again by the undesired `FFSynchronizer`.
Prior to this change this was not an issue as the recursion operation only applied to elements of type `Record`.
Moving the directionality check to occur prior to the recursive operation resolves the issue.
> gateware: fix an order-of-operations bug with cdc.synchronize

- luna/gateware/platform/core.py
Adds the `apollo_gateware_phy` property to `LUNAApolloPlatform` to specify the preferred USB PHY for Apollo gateware.
When the platform does not share a port with Apollo, it defaults to `default_usb_connection`.
See greatscottgadgets/apollo#94.
> gateware.platform: add `apollo_gateware_phy` to `LUNAApolloPlatform`

- applets/clear_endpoint_halt_test.py
- luna/gateware/usb/request/standard.py
- luna/gateware/usb/usb2/control.py
- luna/gateware/usb/usb2/endpoint.py
- luna/gateware/usb/usb2/endpoints/stream.py
- luna/gateware/usb/usb2/request.py
- luna/gateware/usb/usb2/transfer.py
- pyproject.toml
~~This is in draft until https://github.com/greatscottgadgets/python-usb-protocol/pull/45 makes it into a release (and it probably needs a bit of cleanup), but it should work as-is for testing in the meantime.~~
This implements ClearFeature(ENDPOINT_HALT) as required by the USB 2.0 standard, I've also added an applet that can be used to test it out.
> Implement ClearFeature(ENDPOINT_HALT)

- luna/gateware/platform/core.py
This avoids a minor indication bug (https://github.com/greatscottgadgets/apollo/issues/108).
> gateware.platform: Use force_fpga_offline()

- luna/__init__.py
- luna/gateware/platform/__init__.py
- luna/gateware/platform/toolchain.py
While YosysHQ's OSS CAD Suite distribution is readily available it can be somewhat overwhelming to install for beginners.
To make it easier for readers of our gateware tutorials this PR adds support to LUNA for using [YoWASP](https://yowasp.org/)'s WASM-based packages for Yosys and NextPNR if there aren't any other Amaranth-supported toolchains available.
The logic works as follows:
1. Check if platform has all required tools with `platform.has_required_tools()`. If it has, do nothing further and continue to the build.
2. Otherwise, start by setting the `problem` count to `0` and then:
3. Check if the following Python modules can be imported, incrementing the problem count if it cannot.
- `yowasp_yosys`
- `yowasp_nextpnr-<target>` where `<target>` is obtained from …
> Add support for using yowasp when yosys is not available.

- luna/gateware/usb/devices/acm.py
- pyproject.toml
This adds an interface association descriptor to the USB serial device for Windows compatibility.
This depends on https://github.com/greatscottgadgets/python-usb-protocol/pull/52 and a subsequent python-usb-protocol release, so I'll leave as draft for now.
> gateware.usb.devices.acm: include an interface association descriptor
